apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-snapshot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc
