apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-snapshot-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc