apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: evs-snapshot-class
driver: evs.csi.huaweicloud.com
deletionPolicy: Delete
parameters:
  force-create: "false"
