apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  volumeSnapshotClassName: evs-snapshot-class
  source:
    persistentVolumeClaimName: evs-snapshot-pvc
