apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-evs-shareable.ap-southeast-1b
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 12Gi
  storageClassName: evs-share-sc.ap-southeast-1b