apiVersion: v1
kind: Pod
metadata:
  name: inline-pod
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx-inline
      volumeMounts:
        - name: my-csi-volume
          mountPath: /var/lib/www/html
  volumes:
    - name: my-csi-volume
      csi:
        driver: evs.csi.huaweicloud.com
        volumeAttributes:
          capacity: 12Gi # default is 1Gi
        readOnly: false  # default is false
        fsType: ext4 # default is ext4
