---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-obs-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-obs-node
  template:
    metadata:
      labels:
        app: csi-obs-node
    spec:
      serviceAccountName: csi-obs-node-sa
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
      hostPID: true
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=28889
            - --v=5
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=5
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "rm -rf /registration/obs.csi.huaweicloud.com-reg.sock /csi/csi.sock" ]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/obs.csi.huaweicloud.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: obs-csi-plugin
          image: {{image_url}}
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--logtostderr"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-config=$(CLOUD_CONFIG)"
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "/obs-csi/stop-server.sh" ]
          ports:
            - containerPort: 28889
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/obs/cloud-config
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - all
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: csi-tool
              mountPath: /var/lib/csi
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: kubelet-dir
            - name: pass-pods-mount-dir
              mountPath: /mnt/paas/kubernetes/kubelet
              mountPropagation: Bidirectional
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: host-sys
              mountPath: /sys
              readOnly: true
            - name: host-run-udev
              mountPath: /run/udev
              readOnly: true
            - mountPath: /etc/obs/
              name: obs-config
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/obs.csi.huaweicloud.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
          name: kubelet-dir
        - name: pass-pods-mount-dir
          hostPath:
            path: /mnt/paas/kubernetes/kubelet
            type: DirectoryOrCreate
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /sys
            type: Directory
          name: host-sys
        - hostPath:
            path: /run/udev
            type: Directory
          name: host-run-udev
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - secret:
            secretName: cloud-config
          name: obs-config
        - name: csi-tool
          hostPath:
            path: /var/lib/csi
            type: DirectoryOrCreate
