kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sfs.csi.huaweicloud.com 
