apiVersion: v1
kind: Pod
metadata:
  name: test-evs-topology-nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: evs-topology-pvc
        readOnly: false
