apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/data
          name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false
