apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-topology-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: topology-evs-sc
