apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: evs.csi.huaweicloud.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.evs.csi.huaweicloud.com/zone
        values:
          - ap-southeast-1b
parameters:
  type: SSD