apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: csi-data-resize
  volumes:
    - name: csi-data-resize
      persistentVolumeClaim:
        claimName: pvc-resize-demo
        readOnly: false