apiVersion: v1
kind: Pod
metadata:
  name: test-evs-block-nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeDevices:
        - devicePath: /var/lib/www/html
          name: csi-data
  volumes:
    - name: csi-data
      persistentVolumeClaim:
        claimName: evs-block-pvc
        readOnly: false
