apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-evs-block
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc