name: E2E test
on:
  pull_request_target:
    types: [labeled]
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      skip_e2e:
        value: ${{ jobs.before_run_e2e.outputs.skip_e2e }}
      labels:
        value: ${{ jobs.before_run_e2e.outputs.labels }}
jobs:
  before_run_e2e:
    name: before run e2e
    runs-on: ubuntu-latest
    outputs:
      skip_e2e: ${{ steps.check_module.outputs.skip_e2e }}
      labels: ${{ steps.check_module.outputs.labels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0
      - name: Check module
        id: check_module
        shell: bash
        run:
          ./hack/check-module.sh "origin/${{ github.base_ref }}"
  e2e:
    if: ${{ github.repository == 'huaweicloud/huaweicloud-csi-driver' && needs.before_run_e2e.outputs.skip_e2e == 'false' && contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    name: e2e test
    needs: [ before_run_e2e ]
    runs-on: self-hosted
    strategy:
      max-parallel: 3
      matrix:
        k8s: [ 1.20.15, 1.21.13, 1.22.15, 1.23.13, 1.24.7, 1.25.9, 1.26.2, 1.27.1 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install k8s cluster
        run: |
          export CLUSTER_VERSION=${{ matrix.k8s }}
          ./hack/remove-cluster.sh
          ./hack/create-cluster.sh ${{ matrix.k8s }}
      - name: Run e2e
        shell: bash {0}
        run: |
          export ARTIFACTS_PATH=${{ github.workspace }}/e2e-logs/${{ matrix.k8s }}
          ./hack/run-e2e-test.sh "${{ needs.before_run_e2e.outputs.labels }}"
      - name: Remove k8s cluster
        run: ./hack/remove-cluster.sh
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e_log_${{ matrix.k8s }}
          path: ${{ github.workspace }}/e2e-logs/${{ matrix.k8s }}/
